server:
  port: 8086
  servlet:
    context-path: /batch

spring:
  config:
    import: aws-secretsmanager:resident_meeting
  datasource:
    url: jdbc:mysql://${db_host}:3306/resident?rewriteBatchedStatements=true
    username: ${db_username}
    password: ${db_password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    show-sql: true
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: never
  kafka:
    bootstrap-servers: http://kafka-service:9092

batch:
  schedule:
    cron: 0 6 * * * *

